package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as Accession. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.Accession </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class Accession extends GroupOfTests {
	
	public Accession() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.Accession.class
		);
	}
}