package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AliasAndNaming. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.AliasAndNaming </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AliasAndNaming extends GroupOfTests {
	
	public AliasAndNaming() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.AliasAndNaming.class
		);
	}
}