package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AlignFeatureExternalDB. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.AlignFeatureExternalDB </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AlignFeatureExternalDB extends GroupOfTests {
	
	public AlignFeatureExternalDB() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.AlignFeatureExternalDB.class
		);
	}
}