package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AlleleFrequencies. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.AlleleFrequencies </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AlleleFrequencies extends GroupOfTests {
	
	public AlleleFrequencies() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.AlleleFrequencies.class
		);
	}
}