package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AnalysisDescription. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.funcgen.AnalysisDescription </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AnalysisDescription extends GroupOfTests {
	
	public AnalysisDescription() {

		addTest(
			org.ensembl.healthcheck.testcase.funcgen.AnalysisDescription.class
		);
	}
}