package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AnalyseTables. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.AnalyseTables </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AnalyseTables extends GroupOfTests {
	
	public AnalyseTables() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.AnalyseTables.class
		);
	}
}