package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AnalysisXrefs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.AnalysisXrefs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AnalysisXrefs extends GroupOfTests {
	
	public AnalysisXrefs() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.AnalysisXrefs.class
		);
	}
}