package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AncestralSequencesExtraChecks. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.AncestralSequencesExtraChecks </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AncestralSequencesExtraChecks extends GroupOfTests {
	
	public AncestralSequencesExtraChecks() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.AncestralSequencesExtraChecks.class
		);
	}
}