package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as Archive. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.Archive </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class Archive extends GroupOfTests {
	
	public Archive() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.Archive.class
		);
	}
}