package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ArrayXrefs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.funcgen.ArrayXrefs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ArrayXrefs extends GroupOfTests {
	
	public ArrayXrefs() {

		addTest(
			org.ensembl.healthcheck.testcase.funcgen.ArrayXrefs.class
		);
	}
}