package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AssemblyException. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.AssemblyException </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AssemblyException extends GroupOfTests {
	
	public AssemblyException() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.AssemblyException.class
		);
	}
}