package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AssemblyTablesAcrossSpecies. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.AssemblyTablesAcrossSpecies </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AssemblyTablesAcrossSpecies extends GroupOfTests {
	
	public AssemblyTablesAcrossSpecies() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.AssemblyTablesAcrossSpecies.class
		);
	}
}