package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AssemblySeqregion. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.AssemblySeqregion </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AssemblySeqregion extends GroupOfTests {
	
	public AssemblySeqregion() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.AssemblySeqregion.class
		);
	}
}