package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AssemblyMapping. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.AssemblyMapping </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AssemblyMapping extends GroupOfTests {
	
	public AssemblyMapping() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.AssemblyMapping.class
		);
	}
}