package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AssemblyMultipleOverlap. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.AssemblyMultipleOverlap </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AssemblyMultipleOverlap extends GroupOfTests {
	
	public AssemblyMultipleOverlap() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.AssemblyMultipleOverlap.class
		);
	}
}