package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as AttribTypeAcrossSpecies. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.AttribTypeAcrossSpecies </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class AttribTypeAcrossSpecies extends GroupOfTests {
	
	public AttribTypeAcrossSpecies() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.AttribTypeAcrossSpecies.class
		);
	}
}