package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as BigGeneExon. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.BigGeneExon </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class BigGeneExon extends GroupOfTests {
	
	public BigGeneExon() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.BigGeneExon.class
		);
	}
}