package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as Biotypes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.Biotypes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class Biotypes extends GroupOfTests {
	
	public Biotypes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.Biotypes.class
		);
	}
}