package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as BlankEnums. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.BlankEnums </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class BlankEnums extends GroupOfTests {
	
	public BlankEnums() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.BlankEnums.class
		);
	}
}