package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as BlankCoordSystemVersions. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.BlankCoordSystemVersions </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class BlankCoordSystemVersions extends GroupOfTests {
	
	public BlankCoordSystemVersions() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.BlankCoordSystemVersions.class
		);
	}
}