package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as BlankInfoType. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.BlankInfoType </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class BlankInfoType extends GroupOfTests {
	
	public BlankInfoType() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.BlankInfoType.class
		);
	}
}