package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as BlanksInsteadOfNulls. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.BlanksInsteadOfNulls </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class BlanksInsteadOfNulls extends GroupOfTests {
	
	public BlanksInsteadOfNulls() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.BlanksInsteadOfNulls.class
		);
	}
}