package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CanonicalTranscriptCoding. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.CanonicalTranscriptCoding </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CanonicalTranscriptCoding extends GroupOfTests {
	
	public CanonicalTranscriptCoding() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.CanonicalTranscriptCoding.class
		);
	}
}