package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CheckSpeciesSetTag. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckSpeciesSetTag </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CheckSpeciesSetTag extends GroupOfTests {
	
	public CheckSpeciesSetTag() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.CheckSpeciesSetTag.class
		);
	}
}