package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CheckSynteny. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckSynteny </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CheckSynteny extends GroupOfTests {
	
	public CheckSynteny() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.CheckSynteny.class
		);
	}
}