package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CheckSequenceTable. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckSequenceTable </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CheckSequenceTable extends GroupOfTests {
	
	public CheckSequenceTable() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.CheckSequenceTable.class
		);
	}
}