package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CheckTopLevelDnaFrag. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckTopLevelDnaFrag </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CheckTopLevelDnaFrag extends GroupOfTests {
	
	public CheckTopLevelDnaFrag() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.CheckTopLevelDnaFrag.class
		);
	}
}