package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CheckConservationScore. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckConservationScore </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CheckConservationScore extends GroupOfTests {
	
	public CheckConservationScore() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.CheckConservationScore.class
		);
	}
}