package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CheckGenomeDB. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckGenomeDB </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CheckGenomeDB extends GroupOfTests {
	
	public CheckGenomeDB() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.CheckGenomeDB.class
		);
	}
}