package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CheckGenomicAlignGenomeDBs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckGenomicAlignGenomeDBs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CheckGenomicAlignGenomeDBs extends GroupOfTests {
	
	public CheckGenomicAlignGenomeDBs() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.CheckGenomicAlignGenomeDBs.class
		);
	}
}