package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CheckFlatProteinTrees. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckFlatProteinTrees </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CheckFlatProteinTrees extends GroupOfTests {
	
	public CheckFlatProteinTrees() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.CheckFlatProteinTrees.class
		);
	}
}