package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CheckTaxon. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckTaxon </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CheckTaxon extends GroupOfTests {
	
	public CheckTaxon() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.CheckTaxon.class
		);
	}
}