package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CheckHomology. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckHomology </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CheckHomology extends GroupOfTests {
	
	public CheckHomology() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.CheckHomology.class
		);
	}
}