package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ComparePreviousVersionRepeatTypes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionRepeatTypes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ComparePreviousVersionRepeatTypes extends GroupOfTests {
	
	public ComparePreviousVersionRepeatTypes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionRepeatTypes.class
		);
	}
}