package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CompareVariationSchema. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.CompareVariationSchema </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CompareVariationSchema extends GroupOfTests {
	
	public CompareVariationSchema() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.CompareVariationSchema.class
		);
	}
}