package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ComparePreviousVersionCCDS. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionCCDS </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ComparePreviousVersionCCDS extends GroupOfTests {
	
	public ComparePreviousVersionCCDS() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionCCDS.class
		);
	}
}