package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CompareSchema. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.CompareSchema </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CompareSchema extends GroupOfTests {
	
	public CompareSchema() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.CompareSchema.class
		);
	}
}