package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ComparePreviousVersionBiotypes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionBiotypes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ComparePreviousVersionBiotypes extends GroupOfTests {
	
	public ComparePreviousVersionBiotypes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionBiotypes.class
		);
	}
}