package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CompareOldNew. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.mart.CompareOldNew </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CompareOldNew extends GroupOfTests {
	
	public CompareOldNew() {

		addTest(
			org.ensembl.healthcheck.testcase.mart.CompareOldNew.class
		);
	}
}