package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ComparePreviousVersionExonCoords. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionExonCoords </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ComparePreviousVersionExonCoords extends GroupOfTests {
	
	public ComparePreviousVersionExonCoords() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionExonCoords.class
		);
	}
}