package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ComparePreviousVersionTableRows. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionTableRows </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ComparePreviousVersionTableRows extends GroupOfTests {
	
	public ComparePreviousVersionTableRows() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionTableRows.class
		);
	}
}