package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ComparePreviousVersionXrefs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionXrefs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ComparePreviousVersionXrefs extends GroupOfTests {
	
	public ComparePreviousVersionXrefs() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionXrefs.class
		);
	}
}