package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ComparePreviousVersionAnalysisDescriptions. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionAnalysisDescriptions </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ComparePreviousVersionAnalysisDescriptions extends GroupOfTests {
	
	public ComparePreviousVersionAnalysisDescriptions() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionAnalysisDescriptions.class
		);
	}
}