package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ComparePreviousVersionArrayXrefs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.funcgen.ComparePreviousVersionArrayXrefs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ComparePreviousVersionArrayXrefs extends GroupOfTests {
	
	public ComparePreviousVersionArrayXrefs() {

		addTest(
			org.ensembl.healthcheck.testcase.funcgen.ComparePreviousVersionArrayXrefs.class
		);
	}
}