package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ComparePreviousVersionGOXrefs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionGOXrefs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ComparePreviousVersionGOXrefs extends GroupOfTests {
	
	public ComparePreviousVersionGOXrefs() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionGOXrefs.class
		);
	}
}