package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CompareFuncgenSchema. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.funcgen.CompareFuncgenSchema </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CompareFuncgenSchema extends GroupOfTests {
	
	public CompareFuncgenSchema() {

		addTest(
			org.ensembl.healthcheck.testcase.funcgen.CompareFuncgenSchema.class
		);
	}
}