package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ComparePreviousVersionSynonyms. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionSynonyms </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ComparePreviousVersionSynonyms extends GroupOfTests {
	
	public ComparePreviousVersionSynonyms() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionSynonyms.class
		);
	}
}