package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CoordSystemAcrossSpecies. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.CoordSystemAcrossSpecies </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CoordSystemAcrossSpecies extends GroupOfTests {
	
	public CoordSystemAcrossSpecies() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.CoordSystemAcrossSpecies.class
		);
	}
}