package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as core_xrefs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefTypes </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefCategories </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.PredictedXrefs </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionCCDS </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.ExternalDBDescribe </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.GeneDescriptions </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.AnalysisXrefs </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.ExternalSynonymArray </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.GeneStatus </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionSynonyms </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.IdentityXrefCigarLines </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.ExternalDBDisplayName </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.ProjectedXrefs </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefVersions </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionGOXrefs </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefHTML </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefIdentifiers </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.HGNCMultipleGenes </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.InterproDescriptions </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefPrefixes </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.HGNCNumeric </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefLevels </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.DisplayXref </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.HGNCTypes </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.DisplayLabels </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.GOXrefs </li> 
 *   <li> org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionXrefs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CoreXrefs extends GroupOfTests {
	
	public CoreXrefs() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.XrefTypes.class,
			org.ensembl.healthcheck.testcase.generic.XrefCategories.class,
			org.ensembl.healthcheck.testcase.generic.PredictedXrefs.class,
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionCCDS.class,
			org.ensembl.healthcheck.testcase.generic.ExternalDBDescribe.class,
			org.ensembl.healthcheck.testcase.generic.GeneDescriptions.class,
			org.ensembl.healthcheck.testcase.generic.AnalysisXrefs.class,
			org.ensembl.healthcheck.testcase.generic.ExternalSynonymArray.class,
			org.ensembl.healthcheck.testcase.generic.GeneStatus.class,
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionSynonyms.class,
			org.ensembl.healthcheck.testcase.generic.IdentityXrefCigarLines.class,
			org.ensembl.healthcheck.testcase.generic.ExternalDBDisplayName.class,
			org.ensembl.healthcheck.testcase.generic.ProjectedXrefs.class,
			org.ensembl.healthcheck.testcase.generic.XrefVersions.class,
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionGOXrefs.class,
			org.ensembl.healthcheck.testcase.generic.XrefHTML.class,
			org.ensembl.healthcheck.testcase.generic.XrefIdentifiers.class,
			org.ensembl.healthcheck.testcase.generic.HGNCMultipleGenes.class,
			org.ensembl.healthcheck.testcase.generic.InterproDescriptions.class,
			org.ensembl.healthcheck.testcase.generic.XrefPrefixes.class,
			org.ensembl.healthcheck.testcase.generic.HGNCNumeric.class,
			org.ensembl.healthcheck.testcase.generic.XrefLevels.class,
			org.ensembl.healthcheck.testcase.generic.DisplayXref.class,
			org.ensembl.healthcheck.testcase.generic.HGNCTypes.class,
			org.ensembl.healthcheck.testcase.generic.DisplayLabels.class,
			org.ensembl.healthcheck.testcase.generic.GOXrefs.class,
			org.ensembl.healthcheck.testcase.generic.ComparePreviousVersionXrefs.class
		);
	}
}