package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as CoreForeignKeys. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.CoreForeignKeys </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class CoreForeignKeys extends GroupOfTests {
	
	public CoreForeignKeys() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.CoreForeignKeys.class
		);
	}
}