package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DensityFeatures. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.DensityFeatures </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DensityFeatures extends GroupOfTests {
	
	public DensityFeatures() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.DensityFeatures.class
		);
	}
}