package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DeprecatedEgMeta. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.DeprecatedEgMeta </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DeprecatedEgMeta extends GroupOfTests {
	
	public DeprecatedEgMeta() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.DeprecatedEgMeta.class
		);
	}
}