package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DescriptionNewlines. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.DescriptionNewlines </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DescriptionNewlines extends GroupOfTests {
	
	public DescriptionNewlines() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.DescriptionNewlines.class
		);
	}
}