package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DisplayLabels. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.DisplayLabels </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DisplayLabels extends GroupOfTests {
	
	public DisplayLabels() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.DisplayLabels.class
		);
	}
}