package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DisplayXref. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.DisplayXref </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DisplayXref extends GroupOfTests {
	
	public DisplayXref() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.DisplayXref.class
		);
	}
}