package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DisplayXrefId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.DisplayXrefId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DisplayXrefId extends GroupOfTests {
	
	public DisplayXrefId() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.DisplayXrefId.class
		);
	}
}