package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as Ditag. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.Ditag </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class Ditag extends GroupOfTests {
	
	public Ditag() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.Ditag.class
		);
	}
}