package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DNAEmpty. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.DNAEmpty </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DNAEmpty extends GroupOfTests {
	
	public DNAEmpty() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.DNAEmpty.class
		);
	}
}