package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DuplicateMetaKeys. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.DuplicateMetaKeys </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DuplicateMetaKeys extends GroupOfTests {
	
	public DuplicateMetaKeys() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.DuplicateMetaKeys.class
		);
	}
}