package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DuplicateGenes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.DuplicateGenes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DuplicateGenes extends GroupOfTests {
	
	public DuplicateGenes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.DuplicateGenes.class
		);
	}
}