package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DuplicateAssembly. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.DuplicateAssembly </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DuplicateAssembly extends GroupOfTests {
	
	public DuplicateAssembly() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.DuplicateAssembly.class
		);
	}
}