package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DuplicateGenomeDb. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.DuplicateGenomeDb </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DuplicateGenomeDb extends GroupOfTests {
	
	public DuplicateGenomeDb() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.DuplicateGenomeDb.class
		);
	}
}