package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DuplicateAttributes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.DuplicateAttributes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DuplicateAttributes extends GroupOfTests {
	
	public DuplicateAttributes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.DuplicateAttributes.class
		);
	}
}