package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DuplicateTopLevel. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.DuplicateTopLevel </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DuplicateTopLevel extends GroupOfTests {
	
	public DuplicateTopLevel() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.DuplicateTopLevel.class
		);
	}
}