package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DuplicateProteinId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.DuplicateProteinId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DuplicateProteinId extends GroupOfTests {
	
	public DuplicateProteinId() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.DuplicateProteinId.class
		);
	}
}