package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DuplicateExons. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.DuplicateExons </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DuplicateExons extends GroupOfTests {
	
	public DuplicateExons() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.DuplicateExons.class
		);
	}
}