package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as DuplicateXref. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.DuplicateXref </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class DuplicateXref extends GroupOfTests {
	
	public DuplicateXref() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.DuplicateXref.class
		);
	}
}