package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as EgMeta. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.EgMeta </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class EgMeta extends GroupOfTests {
	
	public EgMeta() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.EgMeta.class
		);
	}
}