package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as EgProteinFeatureTranslation. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.EgProteinFeatureTranslation </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class EgProteinFeatureTranslation extends GroupOfTests {
	
	public EgProteinFeatureTranslation() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.EgProteinFeatureTranslation.class
		);
	}
}