package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as EmptyVariationTables. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.EmptyVariationTables </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class EmptyVariationTables extends GroupOfTests {
	
	public EmptyVariationTables() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.EmptyVariationTables.class
		);
	}
}