package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as EmptyTables. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.mart.EmptyTables </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class EmptyTables extends GroupOfTests {
	
	public EmptyTables() {

		addTest(
			org.ensembl.healthcheck.testcase.mart.EmptyTables.class
		);
	}
}