package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as EntrezGeneNumeric. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.EntrezGeneNumeric </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class EntrezGeneNumeric extends GroupOfTests {
	
	public EntrezGeneNumeric() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.EntrezGeneNumeric.class
		);
	}
}