package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ESTStableID. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ESTStableID </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ESTStableID extends GroupOfTests {
	
	public ESTStableID() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ESTStableID.class
		);
	}
}