package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ESTStableIDs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ESTStableIDs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ESTStableIDs extends GroupOfTests {
	
	public ESTStableIDs() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ESTStableIDs.class
		);
	}
}