package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ExonRank. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ExonRank </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ExonRank extends GroupOfTests {
	
	public ExonRank() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ExonRank.class
		);
	}
}