package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ExonTranscriptStartEnd. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ExonTranscriptStartEnd </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ExonTranscriptStartEnd extends GroupOfTests {
	
	public ExonTranscriptStartEnd() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ExonTranscriptStartEnd.class
		);
	}
}