package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ExonStrandOrder. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ExonStrandOrder </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ExonStrandOrder extends GroupOfTests {
	
	public ExonStrandOrder() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ExonStrandOrder.class
		);
	}
}