package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ExonBoundary. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.ExonBoundary </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ExonBoundary extends GroupOfTests {
	
	public ExonBoundary() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.ExonBoundary.class
		);
	}
}