package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ExternalSynonymArray. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ExternalSynonymArray </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ExternalSynonymArray extends GroupOfTests {
	
	public ExternalSynonymArray() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ExternalSynonymArray.class
		);
	}
}