package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ExternalDBDisplayName. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ExternalDBDisplayName </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ExternalDBDisplayName extends GroupOfTests {
	
	public ExternalDBDisplayName() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ExternalDBDisplayName.class
		);
	}
}