package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ExternalDBDescribe. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ExternalDBDescribe </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ExternalDBDescribe extends GroupOfTests {
	
	public ExternalDBDescribe() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ExternalDBDescribe.class
		);
	}
}