package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as FeatureCoords. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.FeatureCoords </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class FeatureCoords extends GroupOfTests {
	
	public FeatureCoords() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.FeatureCoords.class
		);
	}
}