package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as FeatureAnalysis. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.FeatureAnalysis </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class FeatureAnalysis extends GroupOfTests {
	
	public FeatureAnalysis() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.FeatureAnalysis.class
		);
	}
}