package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as FlankingUpDownSeq. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.FlankingUpDownSeq </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class FlankingUpDownSeq extends GroupOfTests {
	
	public FlankingUpDownSeq() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.FlankingUpDownSeq.class
		);
	}
}