package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyHomologyId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeyHomologyId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyHomologyId extends GroupOfTests {
	
	public ForeignKeyHomologyId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeyHomologyId.class
		);
	}
}