package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeySyntenyRegionId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeySyntenyRegionId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeySyntenyRegionId extends GroupOfTests {
	
	public ForeignKeySyntenyRegionId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeySyntenyRegionId.class
		);
	}
}