package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyCoreId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.ForeignKeyCoreId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyCoreId extends GroupOfTests {
	
	public ForeignKeyCoreId() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.ForeignKeyCoreId.class
		);
	}
}