package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyGenomicAlignBlockId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeyGenomicAlignBlockId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyGenomicAlignBlockId extends GroupOfTests {
	
	public ForeignKeyGenomicAlignBlockId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeyGenomicAlignBlockId.class
		);
	}
}