package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeySequenceId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeySequenceId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeySequenceId extends GroupOfTests {
	
	public ForeignKeySequenceId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeySequenceId.class
		);
	}
}