package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyGenomicAlignId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeyGenomicAlignId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyGenomicAlignId extends GroupOfTests {
	
	public ForeignKeyGenomicAlignId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeyGenomicAlignId.class
		);
	}
}