package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyMethodLinkSpeciesSetId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeyMethodLinkSpeciesSetId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyMethodLinkSpeciesSetId extends GroupOfTests {
	
	public ForeignKeyMethodLinkSpeciesSetId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeyMethodLinkSpeciesSetId.class
		);
	}
}