package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyGenomeDbId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeyGenomeDbId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyGenomeDbId extends GroupOfTests {
	
	public ForeignKeyGenomeDbId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeyGenomeDbId.class
		);
	}
}