package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyFamilyId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeyFamilyId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyFamilyId extends GroupOfTests {
	
	public ForeignKeyFamilyId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeyFamilyId.class
		);
	}
}