package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyMemberId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeyMemberId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyMemberId extends GroupOfTests {
	
	public ForeignKeyMemberId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeyMemberId.class
		);
	}
}