package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyTaxonId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeyTaxonId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyTaxonId extends GroupOfTests {
	
	public ForeignKeyTaxonId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeyTaxonId.class
		);
	}
}