package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyMethodLinkSpeciesSetIdGenomicAlignBlock. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeyMethodLinkSpeciesSetIdGenomicAlignBlock </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyMethodLinkSpeciesSetIdGenomicAlignBlock extends GroupOfTests {
	
	public ForeignKeyMethodLinkSpeciesSetIdGenomicAlignBlock() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeyMethodLinkSpeciesSetIdGenomicAlignBlock.class
		);
	}
}