package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyDnafragId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeyDnafragId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyDnafragId extends GroupOfTests {
	
	public ForeignKeyDnafragId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeyDnafragId.class
		);
	}
}