package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ForeignKeyMethodLinkId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.ForeignKeyMethodLinkId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ForeignKeyMethodLinkId extends GroupOfTests {
	
	public ForeignKeyMethodLinkId() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.ForeignKeyMethodLinkId.class
		);
	}
}