package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as FrameshiftAttributes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.FrameshiftAttributes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class FrameshiftAttributes extends GroupOfTests {
	
	public FrameshiftAttributes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.FrameshiftAttributes.class
		);
	}
}