package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as FuncgenAnalysisDescription. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.funcgen.FuncgenAnalysisDescription </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class FuncgenAnalysisDescription extends GroupOfTests {
	
	public FuncgenAnalysisDescription() {

		addTest(
			org.ensembl.healthcheck.testcase.funcgen.FuncgenAnalysisDescription.class
		);
	}
}