package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as FuncgenForeignKeys. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.funcgen.FuncgenForeignKeys </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class FuncgenForeignKeys extends GroupOfTests {
	
	public FuncgenForeignKeys() {

		addTest(
			org.ensembl.healthcheck.testcase.funcgen.FuncgenForeignKeys.class
		);
	}
}