package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as FuncgenStableID. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.funcgen.FuncgenStableID </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class FuncgenStableID extends GroupOfTests {
	
	public FuncgenStableID() {

		addTest(
			org.ensembl.healthcheck.testcase.funcgen.FuncgenStableID.class
		);
	}
}