package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as GenesDisplayable. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.GenesDisplayable </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class GenesDisplayable extends GroupOfTests {
	
	public GenesDisplayable() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.GenesDisplayable.class
		);
	}
}