package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as GeneGC. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.GeneGC </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class GeneGC extends GroupOfTests {
	
	public GeneGC() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.GeneGC.class
		);
	}
}