package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as GeneDescriptionSource. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.GeneDescriptionSource </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class GeneDescriptionSource extends GroupOfTests {
	
	public GeneDescriptionSource() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.GeneDescriptionSource.class
		);
	}
}