package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as GeneDescriptions. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.GeneDescriptions </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class GeneDescriptions extends GroupOfTests {
	
	public GeneDescriptions() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.GeneDescriptions.class
		);
	}
}