package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as GeneDescriptionNewline. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.GeneDescriptionNewline </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class GeneDescriptionNewline extends GroupOfTests {
	
	public GeneDescriptionNewline() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.GeneDescriptionNewline.class
		);
	}
}