package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as GeneCoordSystem. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.GeneCoordSystem </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class GeneCoordSystem extends GroupOfTests {
	
	public GeneCoordSystem() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.GeneCoordSystem.class
		);
	}
}