package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as GeneTranscriptStartEnd. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.GeneTranscriptStartEnd </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class GeneTranscriptStartEnd extends GroupOfTests {
	
	public GeneTranscriptStartEnd() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.GeneTranscriptStartEnd.class
		);
	}
}