package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as GeneStatus. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.GeneStatus </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class GeneStatus extends GroupOfTests {
	
	public GeneStatus() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.GeneStatus.class
		);
	}
}