package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as GeneCount. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.GeneCount </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class GeneCount extends GroupOfTests {
	
	public GeneCount() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.GeneCount.class
		);
	}
}