package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as GeneDescription. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.GeneDescription </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class GeneDescription extends GroupOfTests {
	
	public GeneDescription() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.GeneDescription.class
		);
	}
}