package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as GOXrefs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.GOXrefs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class GOXrefs extends GroupOfTests {
	
	public GOXrefs() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.GOXrefs.class
		);
	}
}