package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as HGNCMultipleGenes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.HGNCMultipleGenes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class HGNCMultipleGenes extends GroupOfTests {
	
	public HGNCMultipleGenes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.HGNCMultipleGenes.class
		);
	}
}