package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as HGNCNumeric. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.HGNCNumeric </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class HGNCNumeric extends GroupOfTests {
	
	public HGNCNumeric() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.HGNCNumeric.class
		);
	}
}