package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as HGNCTypes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.HGNCTypes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class HGNCTypes extends GroupOfTests {
	
	public HGNCTypes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.HGNCTypes.class
		);
	}
}