package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as HitNameFormat. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.HitNameFormat </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class HitNameFormat extends GroupOfTests {
	
	public HitNameFormat() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.HitNameFormat.class
		);
	}
}