package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as IdentityXrefCigarLines. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.IdentityXrefCigarLines </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class IdentityXrefCigarLines extends GroupOfTests {
	
	public IdentityXrefCigarLines() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.IdentityXrefCigarLines.class
		);
	}
}