package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as IdentityXref. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.IdentityXref </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class IdentityXref extends GroupOfTests {
	
	public IdentityXref() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.IdentityXref.class
		);
	}
}