package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as IgiXref. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.IgiXref </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class IgiXref extends GroupOfTests {
	
	public IgiXref() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.IgiXref.class
		);
	}
}