package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as IndividualType. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.IndividualType </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class IndividualType extends GroupOfTests {
	
	public IndividualType() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.IndividualType.class
		);
	}
}