package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as InterproFeature. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.InterproFeature </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class InterproFeature extends GroupOfTests {
	
	public InterproFeature() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.InterproFeature.class
		);
	}
}