package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as InterproDescriptions. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.InterproDescriptions </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class InterproDescriptions extends GroupOfTests {
	
	public InterproDescriptions() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.InterproDescriptions.class
		);
	}
}