package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as IsCurrent. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.IsCurrent </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class IsCurrent extends GroupOfTests {
	
	public IsCurrent() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.IsCurrent.class
		);
	}
}