package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as Karyotype. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.Karyotype </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class Karyotype extends GroupOfTests {
	
	public Karyotype() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.Karyotype.class
		);
	}
}