package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as LogicNamesDisplayable. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.LogicNamesDisplayable </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class LogicNamesDisplayable extends GroupOfTests {
	
	public LogicNamesDisplayable() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.LogicNamesDisplayable.class
		);
	}
}