package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as LowerCaseAnalysisName. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.LowerCaseAnalysisName </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class LowerCaseAnalysisName extends GroupOfTests {
	
	public LowerCaseAnalysisName() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.LowerCaseAnalysisName.class
		);
	}
}