package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as MappingSession. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.MappingSession </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class MappingSession extends GroupOfTests {
	
	public MappingSession() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.MappingSession.class
		);
	}
}