package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as MarkerFeatures. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.MarkerFeatures </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class MarkerFeatures extends GroupOfTests {
	
	public MarkerFeatures() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.MarkerFeatures.class
		);
	}
}