package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as MetaForCompara. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.MetaForCompara </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class MetaForCompara extends GroupOfTests {
	
	public MetaForCompara() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.MetaForCompara.class
		);
	}
}