package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as MetaCrossSpecies. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.MetaCrossSpecies </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class MetaCrossSpecies extends GroupOfTests {
	
	public MetaCrossSpecies() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.MetaCrossSpecies.class
		);
	}
}