package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as MetaCoord. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.funcgen.MetaCoord </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class MetaCoord extends GroupOfTests {
	
	public MetaCoord() {

		addTest(
			org.ensembl.healthcheck.testcase.funcgen.MetaCoord.class
		);
	}
}