package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as Meta. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.Meta </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class Meta extends GroupOfTests {
	
	public Meta() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.Meta.class
		);
	}
}