package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as MTCodonTable. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.MTCodonTable </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class MTCodonTable extends GroupOfTests {
	
	public MTCodonTable() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.MTCodonTable.class
		);
	}
}