package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as MultipleGenomicAlignBlockIds. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.MultipleGenomicAlignBlockIds </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class MultipleGenomicAlignBlockIds extends GroupOfTests {
	
	public MultipleGenomicAlignBlockIds() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.MultipleGenomicAlignBlockIds.class
		);
	}
}