package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as MultipleComponentAssemblyMapping. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.MultipleComponentAssemblyMapping </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class MultipleComponentAssemblyMapping extends GroupOfTests {
	
	public MultipleComponentAssemblyMapping() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.MultipleComponentAssemblyMapping.class
		);
	}
}