package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as NoDuplicateRows. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.mart.NoDuplicateRows </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class NoDuplicateRows extends GroupOfTests {
	
	public NoDuplicateRows() {

		addTest(
			org.ensembl.healthcheck.testcase.mart.NoDuplicateRows.class
		);
	}
}