package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as NullTranscripts. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.NullTranscripts </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class NullTranscripts extends GroupOfTests {
	
	public NullTranscripts() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.NullTranscripts.class
		);
	}
}