package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as NullStrings. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.NullStrings </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class NullStrings extends GroupOfTests {
	
	public NullStrings() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.NullStrings.class
		);
	}
}