package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as PartitionedTables. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.PartitionedTables </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class PartitionedTables extends GroupOfTests {
	
	public PartitionedTables() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.PartitionedTables.class
		);
	}
}