package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as PeptideTranslationAttribs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.PeptideTranslationAttribs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class PeptideTranslationAttribs extends GroupOfTests {
	
	public PeptideTranslationAttribs() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.PeptideTranslationAttribs.class
		);
	}
}