package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as PmatchHits. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.PmatchHits </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class PmatchHits extends GroupOfTests {
	
	public PmatchHits() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.PmatchHits.class
		);
	}
}