package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as post_regulatorybuild. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.funcgen.RegulatoryFeatureTypes </li> 
 *   <li> org.ensembl.healthcheck.testcase.funcgen.FuncgenStableID </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class PostRegulatorybuild extends GroupOfTests {
	
	public PostRegulatorybuild() {

		addTest(
			org.ensembl.healthcheck.testcase.funcgen.RegulatoryFeatureTypes.class,
			org.ensembl.healthcheck.testcase.funcgen.FuncgenStableID.class
		);
	}
}