package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as PredictedXrefs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.PredictedXrefs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class PredictedXrefs extends GroupOfTests {
	
	public PredictedXrefs() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.PredictedXrefs.class
		);
	}
}