package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ProductionBiotypes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ProductionBiotypes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ProductionBiotypes extends GroupOfTests {
	
	public ProductionBiotypes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ProductionBiotypes.class
		);
	}
}