package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ProductionForeignKeys. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.production.ProductionForeignKeys </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ProductionForeignKeys extends GroupOfTests {
	
	public ProductionForeignKeys() {

		addTest(
			org.ensembl.healthcheck.testcase.production.ProductionForeignKeys.class
		);
	}
}