package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ProductionMeta. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ProductionMeta </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ProductionMeta extends GroupOfTests {
	
	public ProductionMeta() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ProductionMeta.class
		);
	}
}