package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ProductionMasterTables. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ProductionMasterTables </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ProductionMasterTables extends GroupOfTests {
	
	public ProductionMasterTables() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ProductionMasterTables.class
		);
	}
}