package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ProjectedXrefGenes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ProjectedXrefGenes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ProjectedXrefGenes extends GroupOfTests {
	
	public ProjectedXrefGenes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ProjectedXrefGenes.class
		);
	}
}