package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ProjectedXrefs. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ProjectedXrefs </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ProjectedXrefs extends GroupOfTests {
	
	public ProjectedXrefs() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ProjectedXrefs.class
		);
	}
}