package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ProteinTranslation. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.ProteinTranslation </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ProteinTranslation extends GroupOfTests {
	
	public ProteinTranslation() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.ProteinTranslation.class
		);
	}
}