package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ProteinCodingGene. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.ProteinCodingGene </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ProteinCodingGene extends GroupOfTests {
	
	public ProteinCodingGene() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.ProteinCodingGene.class
		);
	}
}