package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ProteinFeatureTranslation. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ProteinFeatureTranslation </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ProteinFeatureTranslation extends GroupOfTests {
	
	public ProteinFeatureTranslation() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ProteinFeatureTranslation.class
		);
	}
}