package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as ProteinFeatures. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.ProteinFeatures </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ProteinFeatures extends GroupOfTests {
	
	public ProteinFeatures() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.ProteinFeatures.class
		);
	}
}