package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as Pseudogene. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.Pseudogene </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class Pseudogene extends GroupOfTests {
	
	public Pseudogene() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.Pseudogene.class
		);
	}
}