package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as RegulatoryFeatureTypes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.funcgen.RegulatoryFeatureTypes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class RegulatoryFeatureTypes extends GroupOfTests {
	
	public RegulatoryFeatureTypes() {

		addTest(
			org.ensembl.healthcheck.testcase.funcgen.RegulatoryFeatureTypes.class
		);
	}
}