package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as RepeatConsensus. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.RepeatConsensus </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class RepeatConsensus extends GroupOfTests {
	
	public RepeatConsensus() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.RepeatConsensus.class
		);
	}
}