package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as RepeatFeature. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.RepeatFeature </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class RepeatFeature extends GroupOfTests {
	
	public RepeatFeature() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.RepeatFeature.class
		);
	}
}