package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SampleSetting. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.SampleSetting </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SampleSetting extends GroupOfTests {
	
	public SampleSetting() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.SampleSetting.class
		);
	}
}