package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SchemaType. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.SchemaType </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SchemaType extends GroupOfTests {
	
	public SchemaType() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.SchemaType.class
		);
	}
}