package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SeqRegionAttribAcrossSpecies. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.SeqRegionAttribAcrossSpecies </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SeqRegionAttribAcrossSpecies extends GroupOfTests {
	
	public SeqRegionAttribAcrossSpecies() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.SeqRegionAttribAcrossSpecies.class
		);
	}
}