package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SeqRegionAcrossSpecies. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.SeqRegionAcrossSpecies </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SeqRegionAcrossSpecies extends GroupOfTests {
	
	public SeqRegionAcrossSpecies() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.SeqRegionAcrossSpecies.class
		);
	}
}