package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SeqRegionCoordSystem. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.SeqRegionCoordSystem </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SeqRegionCoordSystem extends GroupOfTests {
	
	public SeqRegionCoordSystem() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.SeqRegionCoordSystem.class
		);
	}
}