package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SeqRegionName. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.SeqRegionName </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SeqRegionName extends GroupOfTests {
	
	public SeqRegionName() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.SeqRegionName.class
		);
	}
}