package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SeqRegionsTopLevel. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.SeqRegionsTopLevel </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SeqRegionsTopLevel extends GroupOfTests {
	
	public SeqRegionsTopLevel() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.SeqRegionsTopLevel.class
		);
	}
}