package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SeqRegionAttribsPresent. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.SeqRegionAttribsPresent </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SeqRegionAttribsPresent extends GroupOfTests {
	
	public SeqRegionAttribsPresent() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.SeqRegionAttribsPresent.class
		);
	}
}