package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SharedDisplayXref. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.SharedDisplayXref </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SharedDisplayXref extends GroupOfTests {
	
	public SharedDisplayXref() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.SharedDisplayXref.class
		);
	}
}