package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SingleDBCollations. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.SingleDBCollations </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SingleDBCollations extends GroupOfTests {
	
	public SingleDBCollations() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.SingleDBCollations.class
		);
	}
}