package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SpeciesNameConsistency. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.SpeciesNameConsistency </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SpeciesNameConsistency extends GroupOfTests {
	
	public SpeciesNameConsistency() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.SpeciesNameConsistency.class
		);
	}
}