package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SpeciesID. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.SpeciesID </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SpeciesID extends GroupOfTests {
	
	public SpeciesID() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.SpeciesID.class
		);
	}
}