package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SpeciesSqlName. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.SpeciesSqlName </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SpeciesSqlName extends GroupOfTests {
	
	public SpeciesSqlName() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.SpeciesSqlName.class
		);
	}
}