package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as StableId. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.StableId </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class StableId extends GroupOfTests {
	
	public StableId() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.StableId.class
		);
	}
}