package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as StableID. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.StableID </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class StableID extends GroupOfTests {
	
	public StableID() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.StableID.class
		);
	}
}