package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as Strand. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.Strand </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class Strand extends GroupOfTests {
	
	public Strand() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.Strand.class
		);
	}
}