package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as SuggestedEgMeta. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.SuggestedEgMeta </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class SuggestedEgMeta extends GroupOfTests {
	
	public SuggestedEgMeta() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.SuggestedEgMeta.class
		);
	}
}