package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as TranscriptsSameName. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.TranscriptsSameName </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class TranscriptsSameName extends GroupOfTests {
	
	public TranscriptsSameName() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.TranscriptsSameName.class
		);
	}
}