package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as TranscriptVariation. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.TranscriptVariation </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class TranscriptVariation extends GroupOfTests {
	
	public TranscriptVariation() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.TranscriptVariation.class
		);
	}
}