package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as TranslationStartEndExon. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.TranslationStartEndExon </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class TranslationStartEndExon extends GroupOfTests {
	
	public TranslationStartEndExon() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.TranslationStartEndExon.class
		);
	}
}