package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as TranslationAttribType. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.eg_core.TranslationAttribType </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class TranslationAttribType extends GroupOfTests {
	
	public TranslationAttribType() {

		addTest(
			org.ensembl.healthcheck.testcase.eg_core.TranslationAttribType.class
		);
	}
}