package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as TranslationStartEnd. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.TranslationStartEnd </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class TranslationStartEnd extends GroupOfTests {
	
	public TranslationStartEnd() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.TranslationStartEnd.class
		);
	}
}