package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as TranscriptsTranslate. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.TranscriptsTranslate </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class TranscriptsTranslate extends GroupOfTests {
	
	public TranscriptsTranslate() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.TranscriptsTranslate.class
		);
	}
}