package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as VariationSet. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.VariationSet </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class VariationSet extends GroupOfTests {
	
	public VariationSet() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.VariationSet.class
		);
	}
}