package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as VariationForeignKeys. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.VariationForeignKeys </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class VariationForeignKeys extends GroupOfTests {
	
	public VariationForeignKeys() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.VariationForeignKeys.class
		);
	}
}