package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as VariationSynonym. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.VariationSynonym </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class VariationSynonym extends GroupOfTests {
	
	public VariationSynonym() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.VariationSynonym.class
		);
	}
}