package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as VFCoordinates. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.variation.VFCoordinates </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class VFCoordinates extends GroupOfTests {
	
	public VFCoordinates() {

		addTest(
			org.ensembl.healthcheck.testcase.variation.VFCoordinates.class
		);
	}
}