package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as XrefIdentifiers. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefIdentifiers </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class XrefIdentifiers extends GroupOfTests {
	
	public XrefIdentifiers() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.XrefIdentifiers.class
		);
	}
}