package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as XrefTypes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefTypes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class XrefTypes extends GroupOfTests {
	
	public XrefTypes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.XrefTypes.class
		);
	}
}