package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as XrefCategories. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefCategories </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class XrefCategories extends GroupOfTests {
	
	public XrefCategories() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.XrefCategories.class
		);
	}
}