package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as XrefVersions. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefVersions </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class XrefVersions extends GroupOfTests {
	
	public XrefVersions() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.XrefVersions.class
		);
	}
}