package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as XrefPrefixes. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefPrefixes </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class XrefPrefixes extends GroupOfTests {
	
	public XrefPrefixes() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.XrefPrefixes.class
		);
	}
}