package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as XrefHTML. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefHTML </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class XrefHTML extends GroupOfTests {
	
	public XrefHTML() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.XrefHTML.class
		);
	}
}