package testgroup.autogeneratedlegacy;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as XrefLevels. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.XrefLevels </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class XrefLevels extends GroupOfTests {
	
	public XrefLevels() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.XrefLevels.class
		);
	}
}