package org.ensembl.healthcheck.testgroup;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as compara_external_foreign_keys. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckGenomeDB </li> 
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckTaxon </li> 
 *   <li> org.ensembl.healthcheck.testcase.compara.CheckTopLevelDnaFrag </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class ComparaExternalForeignKeys extends GroupOfTests {
	
	public ComparaExternalForeignKeys() {

		addTest(
			org.ensembl.healthcheck.testcase.compara.CheckGenomeDB.class,
			org.ensembl.healthcheck.testcase.compara.CheckTaxon.class,
			org.ensembl.healthcheck.testcase.compara.CheckTopLevelDnaFrag.class
		);
	}
}