package org.ensembl.healthcheck.testgroup;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as post_ensmartbuild. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.mart.CompareOldNew </li> 
 *   <li> org.ensembl.healthcheck.testcase.mart.NoDuplicateRows </li> 
 *   <li> org.ensembl.healthcheck.testcase.mart.EmptyTables </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class PostEnsmartbuild extends GroupOfTests {
	
	public PostEnsmartbuild() {

		addTest(
			org.ensembl.healthcheck.testcase.mart.CompareOldNew.class,
			org.ensembl.healthcheck.testcase.mart.NoDuplicateRows.class,
			org.ensembl.healthcheck.testcase.mart.EmptyTables.class
		);
	}
}