package org.ensembl.healthcheck.testgroup;

import org.ensembl.healthcheck.GroupOfTests;

/**
 * These are the tests that register themselves as post_pmatch. The tests are:
 * 
 * <ul>
 *   <li> org.ensembl.healthcheck.testcase.generic.PmatchHits </li> 
 * </ul>
 *
 * @author Autogenerated
 *
 */
public class PostPmatch extends GroupOfTests {
	
	public PostPmatch() {

		addTest(
			org.ensembl.healthcheck.testcase.generic.PmatchHits.class
		);
	}
}