/*
 * GuiTestRunnerFrame.java
 *
 * Created on March 31, 2003, 2:27 PM
 */

package org.ensembl.healthcheck;

import java.util.*;
import javax.swing.*;
import java.awt.Color;

import java.util.logging.*;

/**
 *
 * @author  glenn
 */
public class GuiTestRunnerFrame extends javax.swing.JFrame implements CallbackTarget {
  
  HashMap testButtons = new HashMap();
  
  /** Creates new form GuiTestRunnerFrame */
  public GuiTestRunnerFrame() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    topPanel = new javax.swing.JPanel();
    titleLabel = new javax.swing.JLabel();
    testPanel = new javax.swing.JPanel();
    bottomPanel = new javax.swing.JPanel();
    statusLabel = new javax.swing.JLabel();
    
    setTitle("EnsEMBL HealthCheck");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        exitForm(evt);
      }
    });
    
    topPanel.setBackground(new java.awt.Color(255, 255, 255));
    titleLabel.setFont(new java.awt.Font("SansSerif", 1, 14));
    titleLabel.setIcon(new javax.swing.ImageIcon("/tmp_mnt/net_nfs6/vol1/homes/glenn/work/ensj-healthcheck/images/e-logo.gif"));
    titleLabel.setText("EnsEMBL HealthCheck");
    topPanel.add(titleLabel);
    
    getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);
    
    testPanel.setLayout(new javax.swing.BoxLayout(testPanel, javax.swing.BoxLayout.Y_AXIS));
    
    testPanel.setBackground(new java.awt.Color(255, 255, 255));
    getContentPane().add(testPanel, java.awt.BorderLayout.WEST);
    
    bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    
    bottomPanel.setBackground(new java.awt.Color(153, 153, 255));
    statusLabel.setText("Status ...");
    bottomPanel.add(statusLabel);
    
    getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);
    
    pack();
  }//GEN-END:initComponents
  
  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit(0);
  }//GEN-LAST:event_exitForm
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel bottomPanel;
  private javax.swing.JLabel statusLabel;
  private javax.swing.JPanel testPanel;
  private javax.swing.JLabel titleLabel;
  private javax.swing.JPanel topPanel;
  // End of variables declaration//GEN-END:variables
  
  // -------------------------------------------------------------------------
  /**
   * Update the status bar.
   * @param s The status.
   */
  public void setStatus(String s) {
    
    statusLabel.setText(s);
    
  } // setStatus
  
  // -------------------------------------------------------------------------
  /**
   * Implementation of CallbackTarget; update the relevant part of the GUI when a
   * message is received from the logger.
   */
  public void callback(LogRecord logRecord) {
    
    setStatus(logRecord.getMessage());
    
  } // callback
  
  // -------------------------------------------------------------------------
  /**
   * Initialise the test panel with a list of tests to run.
   */
  public void initTestPanel(List tests, List groupsToRun) {
    
    Iterator it = tests.iterator();
    while (it.hasNext()) {
      EnsTestCase test = (EnsTestCase)it.next();
      if (test.inGroups(groupsToRun)) {
        JButton testButton = new JButton(test.getShortTestName());
        testButton.setBackground(Color.WHITE);
        testButtons.put(test.getTestName(), testButton);
        testButton.setEnabled(false);
        testPanel.add(testButton);
      }
    }
    
    pack();
    
  } // initTestPanel
  
  // -------------------------------------------------------------------------
  
  public void setTestButtonEnabled(String name, boolean enabled) {
    
    ((JButton)testButtons.get(name)).setEnabled(enabled);
    
  } // setTestButtonEnabled
  
  // -------------------------------------------------------------------------
  
  public void setTestButtonColour(String name, Color c) {
    
    ((JButton)testButtons.get(name)).setForeground(c);
    
  } // setTestButtonColor
  // -------------------------------------------------------------------------
  
} // GuiTestRunnerFrame
