/*
 * TestInfoWindow.java
 *
 * Created on April 2, 2003, 10:59 AM
 */

package org.ensembl.healthcheck;

/**
 *
 * @author  glenn
 */
public class TestInfoWindow extends javax.swing.JDialog {
  
  /** Creates new form TestInfoWindow */
  public TestInfoWindow(java.awt.Frame parent, String title, boolean modal) {
    super(parent, modal);
    this.setTitle(title);
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    basePanel = new javax.swing.JPanel();
    infoTextArea = new javax.swing.JTextArea();
    
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        closeDialog(evt);
      }
    });
    
    infoTextArea.setColumns(40);
    infoTextArea.setEditable(false);
    infoTextArea.setRows(10);
    basePanel.add(infoTextArea);
    
    getContentPane().add(basePanel, java.awt.BorderLayout.CENTER);
    
    pack();
  }//GEN-END:initComponents
  
  /** Closes the dialog */
  private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    setVisible(false);
    dispose();
  }//GEN-LAST:event_closeDialog
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    new TestInfoWindow(new javax.swing.JFrame(), "TestInfoWindow", true).show();
  }
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel basePanel;
  private javax.swing.JTextArea infoTextArea;
  // End of variables declaration//GEN-END:variables
 
  public void append(String s) {
    
    infoTextArea.append(s);
    
  } // append
  
  public void clear() {
    
   infoTextArea.setText("");
   
  }
  
}
